#!/bin/sh

case "$(kenv smbios.system.uuid | md5)" in
    4981d75f34fee17042176e45373402b9) pool=atum;;
    43d2bb5ee80e92ab7f089a43857b1c6f) pool=bath;;
    63264a5209271964ed6bd99ec2e4ba3e) pool=ptha;;
    4ab4f280ef5796cd65a8c7c018b675b3) pool=sahu;;
    76544a1889e3f70dc3ba9843de136bde) pool=seth;;
    *) printf '\n\nunknown system... you are on your own from here\n\n'
       exit 1;;
esac

sleep 1
zpool import 2>/dev/null 1>/dev/null
zpool import "$pool" || exit 2

sysctl kern.consmute=1
printf '\033c'
if zfs load-key "$pool" ; then
  sysctl kern.consmute=0
  kenv vfs.root.mountfrom="zfs:$pool/ROOT/default"
  reboot -r
else
  sysctl kern.consmute=0
  exit 3
fi
